language: node_js
node_js:
  - 8.4.0
before_script:
  - npm install -g grunt-cli

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: src
  on:
    branch: master